# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [ ]:
# A Vector is a 1-dimensional array (like a list of numbers).
# A Matrix is a 2-dimensional array (like a table with rows and columns).

**2. How to import `NumPy` library?** 

In [2]:
# To avoid overwriting the output, please code here 
import numpy as np 

**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]

In [1]:
# To avoid overwriting the output, please code here 

In [5]:
list_1 = [1,2,3,4,5]
array_1 = np.array(list_1)
print(array_1)

[1 2 3 4 5]


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [7]:
# To avoid overwriting the output, please code here 

In [6]:
list =[0,1,2,3,4,5]
arr = np.array(np.arange(6))

**5. Generate an `array of "5" zeros` **

In [9]:
# To avoid overwriting the output, please code here 

In [7]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


**6. Generate the following `matrix`.**

In [11]:
# To avoid overwriting the output, please code here 

In [8]:
ones_array = np.ones(5)
print(ones_array)


[1. 1. 1. 1. 1.]


**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [13]:
# To avoid overwriting the output, please code here 

In [10]:
ones_array = np.ones(5)
print(ones_array)


[1. 1. 1. 1. 1.]


**8. Generate an array of "5" tens.**

In [15]:
# To avoid overwriting the output, please code here 

In [9]:
tens_array = np.full(5, 10)
print(tens_array)


[10 10 10 10 10]


**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [17]:
# To avoid overwriting the output, please code here 

In [11]:
even_numbers = np.arange(50, 101, 2)
print(even_numbers)


[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [19]:
# To avoid overwriting the output, please code here 

In [12]:
linspace_array = np.linspace(0, 1, 10)
print(linspace_array)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [21]:
# To avoid overwriting the output, please code here 

In [1]:
# Generating vector array
import numpy as np

vector = np.arange(25)
print(vector)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [2]:
# To avoid overwriting the output, please code here
# matrix_reshape = vector.reshape(5, 5)
matrix_reshape = vector.reshape(5, 5)
print(matrix_reshape)

 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# To avoid overwriting the output, please code here 

In [3]:
# Using shape
vector.shape = (5, 5)
print(vector)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**12. Please generate the following matrix.**

In [27]:
# To avoid overwriting the output, please code here 

In [ ]:
matrix = np.arange(0, 2.4 + 0.1, 0.1).reshape(4, 6)
print(matrix)


array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [29]:
# To avoid overwriting the output, please code here 

In [14]:
import numpy as np

arr = np.linspace(0, 24, 25, dtype=int).reshape(5, 5)
print(arr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**14. What is the main difference between `linspace()` and `arange()`?**

In [ ]:
# arange() takes the 3rd argument as step size.
# linspace() takes the 3rd argument as number of points to generate (not step).


In [ ]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

**15. How to generate a single random integer number using NumPy built-in function?**

In [8]:
# To avoid overwriting the output, please code here 

In [9]:
random_int = np.random.randint(1, 101)  # Random integer from 1 to 100
print(random_int)


32


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [10]:
# To avoid overwriting the output, please code here 

In [11]:
random_matrix = np.random.rand(7, 5)
print(random_matrix)


[[0.54712622 0.01472866 0.87227674 0.2942772  0.36581552]
 [0.2383543  0.49927015 0.16534378 0.37360932 0.69401259]
 [0.27716121 0.60457481 0.11906215 0.52802396 0.74561453]
 [0.59702973 0.63215579 0.9623017  0.6081987  0.1526706 ]
 [0.7164109  0.99942162 0.02279229 0.33600718 0.79865268]
 [0.23126935 0.51196509 0.59487615 0.80781588 0.67233211]
 [0.78066857 0.80823991 0.03992672 0.79665006 0.01586267]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [12]:
# To avoid overwriting the output, please code here 

In [13]:
identity_matrix = np.identity(5)  # You can change 5 to any size
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 