In [4]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7])
print(arr[3])

4


In [ ]:

import numpy as np
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3]) # 3+4=7


7


In [10]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print('2nd elemrent on 1st row ',arr[1,3])

[[1 2 3 4]
 [5 6 7 8]]
2nd elemrent on 1st row  8


In [13]:
import numpy as np

arr = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print( arr)

print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [15]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1, 1, 0])
print(arr)

7
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
