In [1]:
import numpy as np

# Python list থেকে NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [2]:
print(arr.ndim)   # Dimension সংখ্যা
print(arr.shape)  # Row × Column
print(arr.size)   # মোট element সংখ্যা
print(arr.dtype)  # Data type


1
(5,)
5
int64


In [3]:
np.zeros((3,3))     # 3x3 zero matrix
np.ones((2,4))      # 2x4 matrix full of ones
np.full((2,2), 7)   # সব value 7
np.eye(3)           # 3x3 Identity matrix
np.arange(0, 10, 2) # 0 থেকে 10, step 2
np.linspace(0, 1, 5)# 0 থেকে 1, 5 ভাগে


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
arr = np.array([10,20,30,40,50])
print(arr[0])    # প্রথম element
print(arr[-1])   # শেষ element
print(arr[1:4])  # Slice

arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d[0,1])   # Row=0, Col=1 → 2


10
50
[20 30 40]
2


In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)   # [5 7 9]
print(a * b)   # [4 10 18]
print(a ** 2)  # [1 4 9]

print(np.sqrt(a))   # square root
print(np.exp(a))    # exponential


[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


In [6]:
arr = np.array([1,2,3,4,5])

print(arr.sum())   # 15
print(arr.mean())  # 3.0
print(arr.min())   # 1
print(arr.max())   # 5
print(arr.std())   # Standard Deviation


15
3.0
1
5
1.4142135623730951


In [7]:
arr = np.arange(12)       # 0–11 পর্যন্ত
print(arr.reshape(3,4))   # 3x4 matrix
print(arr.reshape(2,2,3)) # 3D array


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.hstack((a,b))) # Horizontal join
print(np.vstack((a,b))) # Vertical join

arr = np.arange(9).reshape(3,3)
print(np.hsplit(arr, 3)) # Split into 3 parts


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [9]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])   # [30 40 50]
print(arr[arr % 20 == 0]) # [20 40]


[30 40 50]
[20 40]


In [10]:
np.random.rand(3,3)       # 0–1 এর মধ্যে random
np.random.randint(1,10,5) # 1–10 এর মধ্যে 5টি সংখ্যা
np.random.randn(3,3)      # Normal distribution


array([[ 0.31017387, -2.2834993 ,  1.42334645],
       [ 1.72191714, -0.02828964, -0.27697912],
       [ 1.02124675, -0.56717652, -0.28915358]])

In [11]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.dot(a,b))   # Matrix multiplication
print(np.linalg.inv(a))  # Inverse
print(np.linalg.det(a))  # Determinant
print(np.linalg.eig(a))  # Eigenvalues & eigenvectors


[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [12]:
np.unique([1,2,2,3])     # Unique values
np.sort([3,1,2])         # Sorting
np.where([1,2,3,4]>2)    # Condition match index
np.clip([1,5,10], 2, 6)  # Limit values (2–6)


TypeError: '>' not supported between instances of 'list' and 'int'

In [13]:
a = np.array([1,2,3])
b = 5
print(a + b)   # [6 7 8]

matrix = np.ones((3,3))
vector = np.array([1,2,3])
print(matrix + vector)


[6 7 8]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
