In [5]:
import pandas as pd 

s = pd.Series([1, 2, 3, 4])
print(s)


0    1
1    2
2    3
3    4
dtype: int64


In [6]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Tanzim', 'Arunima ', 'Karim'],
    'Age': [25, 30, 35, 22, 25, 21],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Dhaka', 'Chittagong', 'Khulna']
}

df = pd.DataFrame(data)
print(df)



       Name  Age         City
0     Alice   25     New York
1       Bob   30  Los Angeles
2   Charlie   35      Chicago
3    Tanzim   22        Dhaka
4  Arunima    25   Chittagong
5     Karim   21       Khulna


In [7]:
import pandas as pd
# Creating a Series
data = pd.Series([10, 20, 30, 40])
print(data)       # Series with default index

0    10
1    20
2    30
3    40
dtype: int64


In [8]:
df

Name  Age         City
0     Alice   25     New York
1       Bob   30  Los Angeles
2   Charlie   35      Chicago
3    Tanzim   22        Dhaka
4  Arunima    25   Chittagong
5     Karim   21       Khulna

In [9]:
df.head()  #top 5 

Name  Age         City
0     Alice   25     New York
1       Bob   30  Los Angeles
2   Charlie   35      Chicago
3    Tanzim   22        Dhaka
4  Arunima    25   Chittagong

In [10]:
df.head()       # Show first 5 rows



Name  Age         City
0     Alice   25     New York
1       Bob   30  Los Angeles
2   Charlie   35      Chicago
3    Tanzim   22        Dhaka
4  Arunima    25   Chittagong

In [11]:
df.tail()       # Show last 5 rows

Name  Age         City
1       Bob   30  Los Angeles
2   Charlie   35      Chicago
3    Tanzim   22        Dhaka
4  Arunima    25   Chittagong
5     Karim   21       Khulna

In [12]:
df.shape        # Rows and columns count


(6, 3)

In [13]:
df.info()       # Info about dataset


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    6 non-null      object
 1   Age     6 non-null      int64 
 2   City    6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes


In [14]:
df.describe()   # Summary statistics

Age
count   6.000000
mean   26.333333
std     5.278889
min    21.000000
25%    22.750000
50%    25.000000
75%    28.750000
max    35.000000

In [15]:
df['Name']             # Select single column
df[['Name', 'Age']]    # Select multiple columns

Name  Age
0     Alice   25
1       Bob   30
2   Charlie   35
3    Tanzim   22
4  Arunima    25
5     Karim   21

In [16]:
df.iloc[4]             # Select row by index

Name      Arunima 
Age             25
City    Chittagong
Name: 4, dtype: object

In [17]:
df.loc[4]              # Select row by label

Name      Arunima 
Age             25
City    Chittagong
Name: 4, dtype: object

In [18]:
# Filter people older than 22
df[df['Age'] > 22]


Name  Age         City
0     Alice   25     New York
1       Bob   30  Los Angeles
2   Charlie   35      Chicago
4  Arunima    25   Chittagong

In [19]:

df['Salary'] = [30000, 35000, 25000, 30000, 23000, 24000]  # Add new column



In [20]:
#df['Salary'] = [30000, 35000, 25000]  # Add new column
df['Age'] = df['Age'] + 1             # Update column
#df.drop('City', axis=1, inplace=True) # Delete column



In [21]:
import numpy as np

# Step 1: Generate 100 linearly spaced points between 50 and 60
arr = np.linspace(50, 60, 100)
print("Original Array:\n", arr)

# Step 2: Convert the vector (1D array) into a (10, 10) matrix
matrix = arr.reshape(10, 10)
print("\nMatrix (10x10):\n", matrix)

# Step 3: Perform the operation (array % 5 == 0)
result = matrix % 5 == 0
print("\nMatrix where elements divisible by 5:\n", result)


Original Array:
 [50.         50.1010101  50.2020202  50.3030303  50.4040404  50.50505051
 50.60606061 50.70707071 50.80808081 50.90909091 51.01010101 51.11111111
 51.21212121 51.31313131 51.41414141 51.51515152 51.61616162 51.71717172
 51.81818182 51.91919192 52.02020202 52.12121212 52.22222222 52.32323232
 52.42424242 52.52525253 52.62626263 52.72727273 52.82828283 52.92929293
 53.03030303 53.13131313 53.23232323 53.33333333 53.43434343 53.53535354
 53.63636364 53.73737374 53.83838384 53.93939394 54.04040404 54.14141414
 54.24242424 54.34343434 54.44444444 54.54545455 54.64646465 54.74747475
 54.84848485 54.94949495 55.05050505 55.15151515 55.25252525 55.35353535
 55.45454545 55.55555556 55.65656566 55.75757576 55.85858586 55.95959596
 56.06060606 56.16161616 56.26262626 56.36363636 56.46464646 56.56565657
 56.66666667 56.76767677 56.86868687 56.96969697 57.07070707 57.17171717
 57.27272727 57.37373737 57.47474747 57.57575758 57.67676768 57.77777778
 57.87878788 57.97979798 58.080808

In [ ]:
import pandas as pd

In [2]:
arr = np.array([[2, 4 , 5 ],[1, 2, 3]])
print(arr)

NameError: name 'np' is not defined

In [1]:
print(arr)

NameError: name 'arr' is not defined

In [3]:
import numpy as np

# Python list থেকে NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [5]:
print(arr2.ndim)   # Dimension সংখ্যা
print(arr2.shape)  # Row × Column
print(arr2.size)   # মোট element সংখ্যা
print(arr2.dtype)  # Data type


2
(2, 3)
6
int64


In [ ]:
np.zeros((3,3))  #3x3 matrix zero-matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((3,3),5)    # সব value 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
np.eye(3)    # 3x3 identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(0,10,2)    # 0 থেকে 10, step 2

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,40,5)  # 0 to 40 -5 division 

array([ 0., 10., 20., 30., 40.])

In [ ]:
arr_4= np.array([10,20,30,40,50])
print(arr_4[0])  # 1st element 

print(arr_4[4])   # last element 
print(arr_4[-1])  # last element 
print(arr[1:4])   # slice 

10
50
50
[2 3 4]


In [20]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d[0,1])   # Row=0, Col=1 → 2

2


In [21]:
# Array Operation 
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)   # [5 7 9]
print(a * b)   # [4 10 18]
print(a ** 2)  # [1 4 9]

print(np.sqrt(a))   # square root
print(np.exp(a))    # exponential


[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


In [22]:
arr = np.array([1,2,3,4,5])

print(arr.sum())   # 15
print(arr.mean())  # 3.0
print(arr.min())   # 1
print(arr.max())   # 5
print(arr.std())   # Standard Deviation


15
3.0
1
5
1.4142135623730951


In [ ]:
arr = np.arange(12)       # 0–11 পর্যন্ত
print(arr.reshape(3,4))   # 3x4 matrix
print(arr.reshape(2,2,3)) # 3D array


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
#Stacking & Splitting 
a = np.array([1,2,3])
b = np.array([4,5,6])



[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [27]:
print(np.hstack((a,b)))   # Horizontal join

[1 2 3 4 5 6]


In [ ]:
print(np.vstack((a,b)))  # Vertical join 

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.arange(9).reshape(3,3)
print(np.hsplit(arr,3))  # Split into 3 parts

[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [33]:
#Boolean Indexing & Filtering
arr_5 = np.array([10, 20, 30, 40, 50])



In [34]:
print(arr_5[arr_4 > 25])

[30 40 50]


In [31]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])   # [30 40 50]
print(arr[arr % 20 == 0]) # [20 40]


[30 40 50]
[20 40]


In [35]:
# Random Numbers 
np.random.rand(3,3)

array([[0.04596809, 0.23332114, 0.23605755],
       [0.53472003, 0.78192225, 0.49390329],
       [0.34819251, 0.74382685, 0.0040897 ]])

In [36]:
np.random.randint(1,10,5) # 1–10 এর মধ্যে 5টি সংখ্যা

array([1, 2, 1, 6, 3], dtype=int32)

In [39]:
np.random.randn(3,3,)      # Normal distribution

array([[-0.95646527, -0.88739275, -0.41077586],
       [-0.33982467,  0.55754625,  0.01433832],
       [ 0.26407907,  0.44411911, -0.04485288]])

In [ ]:
#Linear Algebra
 
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])





[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [41]:
print(np.dot(a,b))   # Matrix multiplication

[[19 22]
 [43 50]]


In [42]:
print(np.linalg.inv(a))  # Inverse

[[-2.   1. ]
 [ 1.5 -0.5]]


In [43]:
print(np.linalg.det(a))  # Determinant

-2.0000000000000004


In [44]:
print(np.linalg.eig(a))  # Eigenvalues & eigenvectors

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
